# Generated by Django 4.1.3 on 2022-11-29 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('telephone', models.CharField(max_length=16, verbose_name='Телефон')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('nearest_metro_stations', models.TextField(blank=True, verbose_name='Ближайшая станция метро')),
                ('opening_hours', models.TextField(blank=True, verbose_name='Часы работы')),
                ('services', models.TextField(blank=True, verbose_name='Сервис')),
                ('review', models.ImageField(blank=True, upload_to='', verbose_name='Отзывы')),
                ('rating', models.ImageField(blank=True, upload_to='', verbose_name='Рейтинг')),
                ('stars', models.ImageField(blank=True, upload_to='', verbose_name='Звезды')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('time_create', models.DateField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateField(auto_now=True, verbose_name='Время изменения')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['time_create', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('stars', models.ImageField(blank=True, upload_to='', verbose_name='Звезды')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.company', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['id'],
            },
        ),
    ]
