# Generated by Django 4.1.3 on 2022-11-29 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, unique=True, verbose_name='Наименование компании')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('services', models.TextField(blank=True, verbose_name='Оказываемые услуги')),
                ('rating', models.IntegerField(blank=True, verbose_name='Цифра рейтинга')),
                ('stars', models.IntegerField(blank=True, verbose_name='Кол-во звезд от 1-5')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Фото')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('time_create', models.DateField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['time_create', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64, unique=True, verbose_name='ФИО')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('stars', models.IntegerField(blank=True, verbose_name='Кол-во звезд от 1-5')),
                ('email', models.EmailField(max_length=254, verbose_name='электронная почта')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mainapp.company')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['id'],
            },
        ),
    ]
