# Generated by Django 4.1.3 on 2022-11-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("mainapp", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="nearest_metro_stations",
            field=models.TextField(blank=True, verbose_name="Ближайшие метро"),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="name",
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name="ФИО"),
        ),
    ]
