# Generated by Django 4.1.3 on 2022-11-29 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['id', 'name'], 'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
    ]
