# Generated by Django 4.1.3 on 2022-11-30 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_company_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.ImageField(upload_to='clinics/images/', verbose_name='Фото'),
        ),
    ]
