# Generated by Django 4.1.3 on 2022-12-29 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_timetable_alter_topbanner_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='stars',
            field=models.IntegerField(choices=[(5, 'Отлично'), (4, 'Хорошо'), (3, 'Удовлетворительно'), (2, 'Плохо'), (1, 'Отрицательно')], default=5, verbose_name='Кол-во звезд от 1-5'),
        ),
        migrations.CreateModel(
            name='CompanyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='clinics/images/', verbose_name='Фото')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mainapp.company')),
            ],
            options={
                'verbose_name': 'Фото компании',
                'verbose_name_plural': 'Фото компаний',
                'ordering': ['id'],
            },
        ),
    ]
