# Generated by Django 4.1.3 on 2023-01-04 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_rename_photo_companyphoto_photoset'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyphoto',
            options={'ordering': ['id'], 'verbose_name': 'Фото клиники', 'verbose_name_plural': 'Фото клиник'},
        ),
        migrations.AddField(
            model_name='services',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(blank=True, max_length=64, unique=True, verbose_name='Наименование клиники'),
        ),
        migrations.AlterField(
            model_name='company',
            name='services',
            field=models.TextField(blank=True, verbose_name='Подробности'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Услуга')),
                ('price', models.PositiveIntegerField(blank=True, max_length=8, verbose_name='Стоимость')),
                ('time_create', models.DateField(auto_now_add=True, verbose_name='Время создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mainapp.company')),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mainapp.services')),
            ],
        ),
    ]
