# Generated by Django 4.1.3 on 2023-01-04 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_companyphoto_options_services_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['id', 'name'], 'verbose_name': 'Прайс', 'verbose_name_plural': 'Прайсы'},
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.PositiveIntegerField(blank=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='services',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликовано'),
        ),
    ]
