# Generated by Django 4.1.3 on 2023-01-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20230105_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='includes',
            field=models.CharField(blank=True, max_length=255, verbose_name='В цену входит'),
        ),
        migrations.AddField(
            model_name='price',
            name='price_max',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Цена, до'),
        ),
        migrations.AddField(
            model_name='price',
            name='unit',
            field=models.CharField(choices=[('', 'Нет'), ('за зуб', 'За Зуб'), ('за ед.', 'За Ед'), ('за шт.', 'За Шт')], default='', max_length=255, verbose_name='единица'),
        ),
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_min',
            field=models.PositiveIntegerField(blank=True, verbose_name='Цена, от'),
        ),
    ]
