# Generated by Django 4.1.3 on 2023-01-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_alter_price_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Услуга'),
        ),
    ]
