# Generated by Django 4.1.3 on 2023-01-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_price_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_max',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена, до'),
        ),
    ]
