# Generated by Django 4.1.3 on 2023-01-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_price_price_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price_min',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Цена, от'),
        ),
    ]
