# Generated by Django 4.1.3 on 2023-01-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_price_price_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='unit',
            field=models.CharField(blank=True, choices=[('', 'Нет'), ('за зуб', 'За Зуб'), ('за ед.', 'За Ед'), ('за шт.', 'За Шт'), ('за 1 снимок', 'За 1 Снимок')], default='', max_length=255, verbose_name='единица'),
        ),
    ]
